version: '3.8'
services:
    webapp:
        build: .
        volumes:
            - .:/var/www/html/
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            - sharifweb
    jaeger:
        image: jaegertracing/all-in-one:1.45
        container_name: 'jaeger'
        environment:
            COLLECTOR_ZIPKIN_HOST_PORT: 9411
            COLLECTOR_OTLP_ENABLED: 'true'
        ports:
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 4317:4317
            - 4318:4318
            - 14250:14250
            - 14268:14268
            - 14269:14269
            - 9411:9411
        networks:
            - sharifweb

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - 'sharifweb-mysql:/var/lib/mysql'
        ports:
            - 3321:3306
        networks:
            - sharifweb

    phpmyadmin:
        image: phpmyadmin
        ports:
            - 9598:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            UPLOAD_LIMIT: 2G
        networks:
            - sharifweb
networks:
    sharifweb:
        external: true
volumes:
    sharifweb-mysql:
        driver: local
