version: '3.8'
services:
  webapp:
    container_name: 'laravel-project-main'
    image: php:8.1.2-apache
    restart: always
    command: 'php ./artisan serve --host=0.0.0.0'
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - laravel-packages
  db:
    container_name: 'laravel-project-db'
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'laravel'
      MYSQL_PASSWORD: 'pass'
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3311:3306
    networks:
      - laravel-packages

  phpmyadmin:
    container_name: 'laravel-project-pma'
    image: phpmyadmin
    restart: always
    ports:
      - 9597:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 2G
    networks:
      - laravel-packages
networks:
  laravel-packages:
    name: laravel-packages
    driver: bridge
