version: '2'
services:
  php:
    image: yiisoftware/yii2-php:5.6-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '84:80'
    networks:
      - yii
  db:
    platform: linux/x86_64
    image: docker.iranserver.com/library/mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'ovh'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    volumes:
      - 'yii-mysql:/var/lib/mysql'
    ports:
      - 3310:3306
    networks:
      - yii

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9596:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - yii
    links:
      - db

networks:
  yii:
    external: true
volumes:
  yii-mysql:
    driver: local